name: release

on:
  # manual trigger
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get version from addon.xml
        id: version
        run: |
          version=$(grep "<addon" plugin.video.filmfriend.de/addon.xml | cut -d '"' -f 6)
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"

      - name: create addon ZIP
        run: zip -D -r plugin.video.filmfriend.de-${{ steps.version.outputs.VERSION }}.zip plugin.video.filmfriend.de

      - name: get changes in version
        id: changelog
        run: sed -n "/^v${{ steps.version.outputs.VERSION }}/, /^v.*/{ /^v.*/!p }" changelog.txt > release_message.txt

      - name: release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: plugin.video.filmfriend.de-${{ steps.version.outputs.VERSION }}.zip
          tag: ${{ steps.version.outputs.VERSION }}
          commit: ${{ github.sha }}
          bodyFile: release_message.txt

      - name: publish to kodinerds
        env:
          USERNAME: ${{ secrets.KODINERDS_USER }}
          PASSWORD: ${{ secrets.KODINERDS_PASSWORD }}
        run: curl -v -H "Content-Type: multipart/form-data" -F upload_info=plugin.video.filmfriend.de-${{ steps.version.outputs.VERSION }}.zip -F upload=@plugin.video.filmfriend.de-${{ steps.version.outputs.VERSION }}.zip -X POST -u "${USERNAME}:${PASSWORD}" https://repo.kodinerds.net/index.php
